#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["rich>=13.0"]
# ///
"""Interactive setup wizard for the GitHub App integration.

Guides you through creating a GitHub App and configuring .env.local.
Re-run to reconfigure, verify, or start the smee webhook proxy.
"""

import argparse
import os
import secrets
import shutil
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import ClassVar

from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.table import Table

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_FILE = REPO_ROOT / "codebox-orchestrator" / ".env.local"
STATE_FILE = Path(__file__).resolve().parent / ".github-setup-state"

console = Console()

# ─── State & env management ────────────────────────────────────


class StateManager:
    """Manages the .github-setup-state file (key=value format)."""

    def __init__(self, path: Path = STATE_FILE) -> None:
        self.path = path
        self.data: dict[str, str] = {}
        self.exists = False

    def load(self) -> None:
        self.data = {}
        self.exists = False
        if not self.path.exists():
            return
        for raw_line in self.path.read_text().splitlines():
            stripped = raw_line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            key, _, value = stripped.partition("=")
            if key:
                self.data[key.strip()] = value.strip()
        self.exists = True

    def save(
        self,
        smee_url: str,
        app_id: str,
        app_slug: str,
        pem_path: str,
        bot_name: str,
    ) -> None:
        timestamp = datetime.now(UTC).astimezone().isoformat()
        self.path.write_text(
            f"# Auto-generated by setup_github.py — do not edit manually\n"
            f"SMEE_URL={smee_url}\n"
            f"APP_ID={app_id}\n"
            f"APP_SLUG={app_slug}\n"
            f"PEM_PATH={pem_path}\n"
            f"BOT_NAME={bot_name}\n"
            f"SETUP_TIMESTAMP={timestamp}\n"
        )
        console.print(f"[dim]State saved to {self.path}[/]")

    def get(self, key: str, default: str = "") -> str:
        return self.data.get(key, default)


class EnvManager:
    """Manages GITHUB_* vars in codebox-orchestrator/.env.local."""

    GITHUB_KEYS: ClassVar[list[str]] = [
        "GITHUB_APP_ID",
        "GITHUB_APP_SLUG",
        "GITHUB_APP_PRIVATE_KEY_PATH",
        "GITHUB_WEBHOOK_SECRET",
        "GITHUB_BOT_NAME",
    ]

    def __init__(self, path: Path = ENV_FILE) -> None:
        self.path = path
        self.vars: dict[str, str] = {}
        self.has_config = False

    def load(self) -> None:
        self.vars = {}
        self.has_config = False
        if not self.path.exists():
            return
        for line in self.path.read_text().splitlines():
            for key in self.GITHUB_KEYS:
                if line.startswith(f"{key}="):
                    self.vars[key] = line.split("=", 1)[1]
        self.has_config = bool(self.vars.get("GITHUB_APP_ID"))

    def get(self, key: str, default: str = "") -> str:
        return self.vars.get(key, default)

    def write_github_config(self, config: dict[str, str]) -> None:
        """Write GitHub config to .env.local, replacing any existing GitHub vars."""
        lines: list[str] = []
        if self.path.exists():
            lines = [
                line
                for line in self.path.read_text().splitlines()
                if not any(line.startswith(f"{k}=") for k in self.GITHUB_KEYS)
                and line != "# GitHub App integration"
            ]
            # Remove trailing blank lines
            while lines and not lines[-1].strip():
                lines.pop()

        lines.append("")
        lines.append("# GitHub App integration")
        for key, value in config.items():
            lines.append(f"{key}={value}")
        lines.append("")

        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text("\n".join(lines))


# ─── Status & verification ──────────────────────────────────────


def show_status(state: StateManager, env: EnvManager) -> None:
    table = Table(show_header=False, box=None, padding=(0, 2))
    table.add_column("Key", style="bold")
    table.add_column("Value", style="cyan")

    app_id = env.get("GITHUB_APP_ID") or state.get("APP_ID") or "(not set)"
    app_slug = env.get("GITHUB_APP_SLUG") or state.get("APP_SLUG") or "(not set)"
    pem_path = env.get("GITHUB_APP_PRIVATE_KEY_PATH") or state.get("PEM_PATH") or "(not set)"
    bot_name = env.get("GITHUB_BOT_NAME") or state.get("BOT_NAME") or "(not set)"
    smee_url = state.get("SMEE_URL") or "(not saved)"

    secret = env.get("GITHUB_WEBHOOK_SECRET")
    secret_display = f"{secret[:8]}..." if secret else "(not set)"

    table.add_row("App ID", app_id)
    table.add_row("App slug", app_slug)
    table.add_row("Bot name", bot_name)
    table.add_row("Private key", pem_path)
    table.add_row("Webhook secret", secret_display)
    table.add_row("Smee URL", smee_url)

    panel = Panel(table, title="GitHub App Configuration", border_style="cyan")
    console.print(panel)

    timestamp = state.get("SETUP_TIMESTAMP")
    if timestamp:
        console.print(f"[dim]Last configured: {timestamp}[/]")


def verify_config(state: StateManager, env: EnvManager) -> None:
    console.print()
    console.print(Panel("[bold]Verifying Configuration[/]", border_style="cyan", expand=False))
    console.print()

    all_ok = True

    for key in EnvManager.GITHUB_KEYS:
        value = env.get(key)
        if value:
            console.print(f"  [green]\u2713[/] {key} is set")
        else:
            console.print(
                f"  [yellow]\u2717[/] {key} is {'empty' if env.path.exists() else 'MISSING'}"
            )
            all_ok = False

    # Check PEM file
    pem_path = env.get("GITHUB_APP_PRIVATE_KEY_PATH")
    if pem_path and Path(pem_path).expanduser().exists():
        console.print("  [green]\u2713[/] Private key file exists")
    elif pem_path:
        console.print(f"  [red]\u2717[/] Private key file NOT FOUND: {pem_path}")
        all_ok = False
    else:
        console.print("  [yellow]\u2717[/] Private key path not set")
        all_ok = False

    # Check smee URL
    smee_url = state.get("SMEE_URL")
    if smee_url:
        console.print(f"  [green]\u2713[/] Smee URL saved: {smee_url}")
    else:
        console.print("  [yellow]\u2717[/] Smee URL not saved (run setup to save it)")

    console.print()
    if all_ok:
        console.print("[bold green]All checks passed![/]")
    else:
        console.print("[bold yellow]Some checks failed — run setup to fix.[/]")


# ─── Smee proxy ─────────────────────────────────────────────────


def start_smee(state: StateManager) -> None:
    url = state.get("SMEE_URL")
    if not url:
        console.print("No smee URL saved.")
        url = Prompt.ask("Enter your smee.io URL")
        # Save just the smee URL to state
        lines: list[str] = []
        if state.path.exists():
            lines = state.path.read_text().splitlines()
            lines = [ln for ln in lines if not ln.startswith("SMEE_URL=")]
        else:
            lines = ["# Auto-generated by setup_github.py"]
        lines.append(f"SMEE_URL={url}")
        state.path.write_text("\n".join(lines) + "\n")

    if not shutil.which("pnpm"):
        console.print(
            Panel(
                "[bold]pnpm is required to run smee-client.[/]\n\n"
                "Install: [cyan]curl -fsSL https://get.pnpm.io/install.sh | sh[/]",
                title="Error",
                border_style="red",
            )
        )
        sys.exit(1)

    target = "http://localhost:8080/api/github/webhook"
    console.print(
        f"Starting smee proxy: [cyan]{url}[/] -> {target}\n[dim]Press Ctrl+C to stop[/]\n"
    )

    smee_cmd = ["pnpm", "dlx", "smee-client", "-u", url, "--target", target]

    # Use os.execvp on Unix to replace the process (like bash exec),
    # fall back to subprocess on Windows.
    if sys.platform != "win32":
        os.execvp("pnpm", smee_cmd)  # noqa: S606, S607
    else:
        result = subprocess.run(smee_cmd, check=False)  # noqa: S603
        sys.exit(result.returncode)


# ─── Wizard steps ───────────────────────────────────────────────


def _step_prerequisites() -> None:
    console.print()
    console.print(Panel("[bold]Step 1: Prerequisites[/]", border_style="cyan", expand=False))
    console.print()

    if not shutil.which("pnpm"):
        console.print(
            "[yellow]pnpm not found.[/] It's needed to run the smee webhook proxy.\n"
            "Install: [cyan]curl -fsSL https://get.pnpm.io/install.sh | sh[/]\n"
        )

    container_engine = None
    if shutil.which("docker"):
        container_engine = "docker"
    elif shutil.which("podman"):
        container_engine = "podman"
    else:
        console.print(
            Panel(
                "[bold]Neither docker nor podman found.[/]\nA container engine is required.",
                title="Error",
                border_style="red",
            )
        )
        sys.exit(1)

    console.print(f"  [green]\u2713[/] Using container engine: [bold]{container_engine}[/]")
    console.print("  [green]\u2713[/] Prerequisites OK")


def _step_smee_url(defaults: dict[str, str]) -> str:
    console.print()
    console.print(
        Panel("[bold]Step 2: Webhook Tunnel (smee.io)[/]", border_style="cyan", expand=False)
    )
    console.print()

    if defaults["smee_url"]:
        console.print(f"Previously used smee URL: [cyan]{defaults['smee_url']}[/]\n")

    console.print(
        "GitHub needs a public URL to deliver webhooks. smee.io proxies them to localhost.\n"
    )

    if not defaults["smee_url"]:
        console.print(
            "1. Go to [cyan]https://smee.io[/] and click 'Start a new channel'\n"
            "2. Copy the channel URL (e.g. https://smee.io/AbCdEfGhIjKl)\n"
        )

    smee_url = Prompt.ask("Smee.io channel URL", default=defaults["smee_url"] or "")

    if smee_url and not smee_url.startswith("https://smee.io/"):
        console.print("[yellow]That doesn't look like a smee.io URL, but continuing anyway.[/]")

    return smee_url


def _step_github_app_guide(smee_url: str, defaults: dict[str, str], *, use_defaults: bool) -> None:
    console.print()
    console.print(Panel("[bold]Step 3: GitHub App[/]", border_style="cyan", expand=False))
    console.print()

    if use_defaults and defaults["app_id"]:
        console.print(
            f"Existing app: [bold]{defaults['app_slug']}[/] (ID: [cyan]{defaults['app_id']}[/])\n"
        )
        console.print("Verify/update these settings on your GitHub App's settings page:\n")
    else:
        console.print("Go to: [cyan]https://github.com/settings/apps/new[/]\n")

    settings = Table(show_header=False, box=None, padding=(0, 2))
    settings.add_column("Setting", style="bold")
    settings.add_column("Value")
    settings.add_row("App name", "codebox-dev (or your preferred name)")
    settings.add_row("Homepage URL", "http://localhost:3000")
    settings.add_row("Webhook URL", f"[cyan]{smee_url}[/]")
    settings.add_row("Setup URL", "[cyan]http://localhost:8080/api/github/callback[/]")
    settings.add_row("", "[dim](check 'Redirect on update')[/]")
    console.print(settings)

    console.print()
    perms = Table(title="Permissions", show_header=False, box=None, padding=(0, 2))
    perms.add_column("Permission", style="bold")
    perms.add_column("Level")
    perms.add_row("Contents", "Read & Write")
    perms.add_row("Pull requests", "Read & Write")
    perms.add_row("Issues", "Read & Write")
    perms.add_row("Commit statuses", "Read & Write")
    perms.add_row("Metadata", "Read")
    console.print(perms)

    console.print()
    console.print(
        "[bold]Subscribe to events:[/] Issue comment, Pull request review comment, Installation"
    )
    console.print()
    console.print(
        "After creating the app, generate a private key (button at the bottom\n"
        "of the app settings page). It will download a .pem file.\n"
    )

    if not use_defaults or not defaults["app_id"]:
        Prompt.ask(
            "[dim]Press Enter when you've created the app and downloaded the private key[/]",
            default="",
        )


def _step_credentials(defaults: dict[str, str]) -> dict[str, str]:
    console.print()
    console.print(
        Panel("[bold]Step 4: Configure Credentials[/]", border_style="cyan", expand=False)
    )
    console.print()

    console.print("You can find these values on your GitHub App's settings page.\n")

    app_id = Prompt.ask(
        "GitHub App ID (number from the app's About section)",
        default=defaults["app_id"] or None,
    )
    app_slug = Prompt.ask(
        "GitHub App slug (the URL-friendly name)",
        default=defaults["app_slug"] or None,
    )

    console.print()
    console.print("Webhook secret — used to verify webhook signatures.")

    if defaults["webhook_secret"]:
        webhook_secret = Prompt.ask(
            "Webhook secret (Enter to keep existing)",
            default=defaults["webhook_secret"],
        )
    else:
        generated_secret = secrets.token_hex(20)
        console.print(f"  Auto-generated: [dim]{generated_secret}[/]")
        webhook_secret = Prompt.ask(
            "Webhook secret (Enter to use generated, or paste your own)",
            default=generated_secret,
        )

    console.print()
    console.print(
        "[yellow]Important:[/] Set this same webhook secret in your GitHub App settings\n"
        "  (GitHub App settings > General > Webhook secret)\n"
    )

    pem_path = Prompt.ask(
        "Path to the downloaded .pem private key file",
        default=defaults["pem_path"] or None,
    )

    pem_resolved = Path(pem_path).expanduser()
    if not pem_resolved.exists():
        console.print(
            Panel(
                f"[bold]File not found:[/] {pem_resolved}\n\n"
                "Please check the path and re-run this script.",
                title="Error",
                border_style="red",
            )
        )
        sys.exit(1)

    default_bot = defaults["bot_name"] or app_slug
    bot_name = Prompt.ask(
        "Bot trigger name (users will type @<name> in comments)",
        default=default_bot,
    )

    return {
        "app_id": app_id,
        "app_slug": app_slug,
        "webhook_secret": webhook_secret,
        "pem_path": pem_path,
        "bot_name": bot_name,
    }


def _step_write_config(
    env: EnvManager, state: StateManager, smee_url: str, creds: dict[str, str]
) -> None:
    console.print()
    console.print(Panel("[bold]Step 5: Write Configuration[/]", border_style="cyan", expand=False))
    console.print()

    if env.has_config:
        console.print(f"[yellow]GitHub configuration already exists in {ENV_FILE}[/]")
        if not Confirm.ask("Overwrite existing GitHub settings?", default=True):
            console.print("Aborted. No changes made.")
            sys.exit(0)

    config = {
        "GITHUB_APP_ID": creds["app_id"],
        "GITHUB_APP_SLUG": creds["app_slug"],
        "GITHUB_APP_PRIVATE_KEY_PATH": creds["pem_path"],
        "GITHUB_WEBHOOK_SECRET": creds["webhook_secret"],
        "GITHUB_BOT_NAME": creds["bot_name"],
    }
    env.write_github_config(config)
    console.print(f"[green]Written to {ENV_FILE}[/]\n")

    result_table = Table(show_header=False, box=None, padding=(0, 2))
    result_table.add_column("Key", style="bold")
    result_table.add_column("Value", style="cyan")
    for key, value in config.items():
        display = f"{value[:8]}..." if key == "GITHUB_WEBHOOK_SECRET" else value
        result_table.add_row(key, display)
    console.print(result_table)

    state.save(
        smee_url=smee_url,
        app_id=creds["app_id"],
        app_slug=creds["app_slug"],
        pem_path=creds["pem_path"],
        bot_name=creds["bot_name"],
    )


def _step_next_steps(state: StateManager, smee_url: str, app_slug: str, bot_name: str) -> None:
    console.print()
    next_steps = (
        "1. Start the webhook tunnel (keep running in a separate terminal):\n\n"
        f"   [bold]pnpm dlx smee-client -u {smee_url} --target http://localhost:8080/api/github/webhook[/]\n"
        f"   [dim]or: uv run scripts/setup_github.py --smee[/]\n\n"
        "2. Build the sandbox image (if not already done):\n\n"
        "   [bold]uv run scripts/build_sandbox.py[/]\n\n"
        "3. Start the orchestrator:\n\n"
        "   [bold]cd codebox-orchestrator && python -m codebox_orchestrator[/]\n\n"
        f"4. Install the GitHub App on a test repo:\n\n"
        f"   [bold]https://github.com/apps/{app_slug}/installations/new[/]\n\n"
        "5. Add the installation via the web UI (http://localhost:3000/settings/github)\n"
        "   or manually via the API.\n\n"
        f"6. Comment on an issue to trigger the agent:\n\n"
        f"   [bold]@{bot_name} implement this feature[/]"
    )
    console.print(Panel(next_steps, title="Next Steps", border_style="green"))
    console.print("[bold green]Setup complete![/]\n")

    if Confirm.ask("Start the smee webhook proxy now?", default=True):
        console.print()
        start_smee(state)


def run_wizard(state: StateManager, env: EnvManager, *, use_defaults: bool) -> None:
    defaults = {
        "app_id": env.get("GITHUB_APP_ID") or state.get("APP_ID"),
        "app_slug": env.get("GITHUB_APP_SLUG") or state.get("APP_SLUG") or "codebox-dev",
        "pem_path": env.get("GITHUB_APP_PRIVATE_KEY_PATH") or state.get("PEM_PATH"),
        "webhook_secret": env.get("GITHUB_WEBHOOK_SECRET"),
        "bot_name": env.get("GITHUB_BOT_NAME") or state.get("BOT_NAME"),
        "smee_url": state.get("SMEE_URL"),
    }

    _step_prerequisites()
    smee_url = _step_smee_url(defaults)
    _step_github_app_guide(smee_url, defaults, use_defaults=use_defaults)
    creds = _step_credentials(defaults)
    _step_write_config(env, state, smee_url, creds)
    _step_next_steps(state, smee_url, creds["app_slug"], creds["bot_name"])


# ─── Menu ───────────────────────────────────────────────────────


def show_menu(state: StateManager, env: EnvManager) -> None:
    console.print()
    console.print("[bold]What would you like to do?[/]\n")
    console.print("  1) Verify configuration")
    console.print("  2) Reconfigure (wizard with current values as defaults)")
    console.print("  3) Start smee proxy")
    console.print("  4) Fresh setup (start from scratch)")
    console.print("  q) Quit\n")

    choice = Prompt.ask("Choose", choices=["1", "2", "3", "4", "q"])

    match choice:
        case "1":
            verify_config(state, env)
        case "2":
            run_wizard(state, env, use_defaults=True)
        case "3":
            start_smee(state)
        case "4":
            run_wizard(state, env, use_defaults=False)
        case "q":
            pass


# ─── CLI & main ─────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Interactive setup wizard for the GitHub App integration."
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--status", action="store_true", help="Show current configuration")
    group.add_argument("--verify", action="store_true", help="Verify all settings are correct")
    group.add_argument("--smee", action="store_true", help="Start the smee webhook proxy")
    group.add_argument(
        "--fresh", action="store_true", help="Run the full setup wizard from scratch"
    )
    args = parser.parse_args()

    state = StateManager()
    state.load()

    env = EnvManager()
    env.load()

    # Dispatch CLI flags
    if args.status:
        show_status(state, env)
    elif args.verify:
        verify_config(state, env)
    elif args.smee:
        start_smee(state)
    elif args.fresh:
        run_wizard(state, env, use_defaults=False)
    elif env.has_config:
        # Interactive mode — already configured
        show_status(state, env)
        show_menu(state, env)
    elif state.exists:
        console.print()
        console.print(
            "[dim]Found previous setup state but GitHub vars are not in .env.local.[/]\n"
        )
        console.print("  1) Reconfigure using saved defaults")
        console.print("  2) Fresh setup")
        console.print("  q) Quit\n")

        choice = Prompt.ask("Choose", choices=["1", "2", "q"])
        match choice:
            case "1":
                run_wizard(state, env, use_defaults=True)
            case "2":
                run_wizard(state, env, use_defaults=False)
            case "q":
                pass
    else:
        run_wizard(state, env, use_defaults=False)


if __name__ == "__main__":
    main()
