/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as ProjectsProjectSlugRouteRouteImport } from './routes/projects/$projectSlug/route'
import { Route as ProjectsProjectSlugIndexRouteImport } from './routes/projects/$projectSlug/index'
import { Route as ProjectsProjectSlugSettingsRouteRouteImport } from './routes/projects/$projectSlug/settings/route'
import { Route as ProjectsProjectSlugSettingsIndexRouteImport } from './routes/projects/$projectSlug/settings/index'
import { Route as ProjectsProjectSlugSettingsTavilyRouteImport } from './routes/projects/$projectSlug/settings/tavily'
import { Route as ProjectsProjectSlugSettingsMembersRouteImport } from './routes/projects/$projectSlug/settings/members'
import { Route as ProjectsProjectSlugSettingsLlmProfilesRouteImport } from './routes/projects/$projectSlug/settings/llm-profiles'
import { Route as ProjectsProjectSlugSettingsGithubRouteImport } from './routes/projects/$projectSlug/settings/github'
import { Route as ProjectsProjectSlugBoxesCreateRouteImport } from './routes/projects/$projectSlug/boxes/create'
import { Route as ProjectsProjectSlugBoxesBoxIdRouteRouteImport } from './routes/projects/$projectSlug/boxes/$boxId/route'
import { Route as ProjectsProjectSlugBoxesBoxIdIndexRouteImport } from './routes/projects/$projectSlug/boxes/$boxId/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ProjectsProjectSlugRouteRoute =
  ProjectsProjectSlugRouteRouteImport.update({
    id: '/projects/$projectSlug',
    path: '/projects/$projectSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectSlugIndexRoute =
  ProjectsProjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectSlugRouteRoute,
  } as any)
const ProjectsProjectSlugSettingsRouteRoute =
  ProjectsProjectSlugSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectSlugRouteRoute,
  } as any)
const ProjectsProjectSlugSettingsIndexRoute =
  ProjectsProjectSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectSlugSettingsRouteRoute,
  } as any)
const ProjectsProjectSlugSettingsTavilyRoute =
  ProjectsProjectSlugSettingsTavilyRouteImport.update({
    id: '/tavily',
    path: '/tavily',
    getParentRoute: () => ProjectsProjectSlugSettingsRouteRoute,
  } as any)
const ProjectsProjectSlugSettingsMembersRoute =
  ProjectsProjectSlugSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProjectsProjectSlugSettingsRouteRoute,
  } as any)
const ProjectsProjectSlugSettingsLlmProfilesRoute =
  ProjectsProjectSlugSettingsLlmProfilesRouteImport.update({
    id: '/llm-profiles',
    path: '/llm-profiles',
    getParentRoute: () => ProjectsProjectSlugSettingsRouteRoute,
  } as any)
const ProjectsProjectSlugSettingsGithubRoute =
  ProjectsProjectSlugSettingsGithubRouteImport.update({
    id: '/github',
    path: '/github',
    getParentRoute: () => ProjectsProjectSlugSettingsRouteRoute,
  } as any)
const ProjectsProjectSlugBoxesCreateRoute =
  ProjectsProjectSlugBoxesCreateRouteImport.update({
    id: '/boxes/create',
    path: '/boxes/create',
    getParentRoute: () => ProjectsProjectSlugRouteRoute,
  } as any)
const ProjectsProjectSlugBoxesBoxIdRouteRoute =
  ProjectsProjectSlugBoxesBoxIdRouteRouteImport.update({
    id: '/boxes/$boxId',
    path: '/boxes/$boxId',
    getParentRoute: () => ProjectsProjectSlugRouteRoute,
  } as any)
const ProjectsProjectSlugBoxesBoxIdIndexRoute =
  ProjectsProjectSlugBoxesBoxIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectSlugBoxesBoxIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/users': typeof UsersRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugRouteRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/projects/$projectSlug/settings': typeof ProjectsProjectSlugSettingsRouteRouteWithChildren
  '/projects/$projectSlug/': typeof ProjectsProjectSlugIndexRoute
  '/projects/$projectSlug/boxes/$boxId': typeof ProjectsProjectSlugBoxesBoxIdRouteRouteWithChildren
  '/projects/$projectSlug/boxes/create': typeof ProjectsProjectSlugBoxesCreateRoute
  '/projects/$projectSlug/settings/github': typeof ProjectsProjectSlugSettingsGithubRoute
  '/projects/$projectSlug/settings/llm-profiles': typeof ProjectsProjectSlugSettingsLlmProfilesRoute
  '/projects/$projectSlug/settings/members': typeof ProjectsProjectSlugSettingsMembersRoute
  '/projects/$projectSlug/settings/tavily': typeof ProjectsProjectSlugSettingsTavilyRoute
  '/projects/$projectSlug/settings/': typeof ProjectsProjectSlugSettingsIndexRoute
  '/projects/$projectSlug/boxes/$boxId/': typeof ProjectsProjectSlugBoxesBoxIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/users': typeof UsersRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugIndexRoute
  '/projects/$projectSlug/boxes/create': typeof ProjectsProjectSlugBoxesCreateRoute
  '/projects/$projectSlug/settings/github': typeof ProjectsProjectSlugSettingsGithubRoute
  '/projects/$projectSlug/settings/llm-profiles': typeof ProjectsProjectSlugSettingsLlmProfilesRoute
  '/projects/$projectSlug/settings/members': typeof ProjectsProjectSlugSettingsMembersRoute
  '/projects/$projectSlug/settings/tavily': typeof ProjectsProjectSlugSettingsTavilyRoute
  '/projects/$projectSlug/settings': typeof ProjectsProjectSlugSettingsIndexRoute
  '/projects/$projectSlug/boxes/$boxId': typeof ProjectsProjectSlugBoxesBoxIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/users': typeof UsersRoute
  '/projects/$projectSlug': typeof ProjectsProjectSlugRouteRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/projects/$projectSlug/settings': typeof ProjectsProjectSlugSettingsRouteRouteWithChildren
  '/projects/$projectSlug/': typeof ProjectsProjectSlugIndexRoute
  '/projects/$projectSlug/boxes/$boxId': typeof ProjectsProjectSlugBoxesBoxIdRouteRouteWithChildren
  '/projects/$projectSlug/boxes/create': typeof ProjectsProjectSlugBoxesCreateRoute
  '/projects/$projectSlug/settings/github': typeof ProjectsProjectSlugSettingsGithubRoute
  '/projects/$projectSlug/settings/llm-profiles': typeof ProjectsProjectSlugSettingsLlmProfilesRoute
  '/projects/$projectSlug/settings/members': typeof ProjectsProjectSlugSettingsMembersRoute
  '/projects/$projectSlug/settings/tavily': typeof ProjectsProjectSlugSettingsTavilyRoute
  '/projects/$projectSlug/settings/': typeof ProjectsProjectSlugSettingsIndexRoute
  '/projects/$projectSlug/boxes/$boxId/': typeof ProjectsProjectSlugBoxesBoxIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/login'
    | '/users'
    | '/projects/$projectSlug'
    | '/settings/account'
    | '/settings/appearance'
    | '/projects/'
    | '/settings/'
    | '/projects/$projectSlug/settings'
    | '/projects/$projectSlug/'
    | '/projects/$projectSlug/boxes/$boxId'
    | '/projects/$projectSlug/boxes/create'
    | '/projects/$projectSlug/settings/github'
    | '/projects/$projectSlug/settings/llm-profiles'
    | '/projects/$projectSlug/settings/members'
    | '/projects/$projectSlug/settings/tavily'
    | '/projects/$projectSlug/settings/'
    | '/projects/$projectSlug/boxes/$boxId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/users'
    | '/settings/account'
    | '/settings/appearance'
    | '/projects'
    | '/settings'
    | '/projects/$projectSlug'
    | '/projects/$projectSlug/boxes/create'
    | '/projects/$projectSlug/settings/github'
    | '/projects/$projectSlug/settings/llm-profiles'
    | '/projects/$projectSlug/settings/members'
    | '/projects/$projectSlug/settings/tavily'
    | '/projects/$projectSlug/settings'
    | '/projects/$projectSlug/boxes/$boxId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/login'
    | '/users'
    | '/projects/$projectSlug'
    | '/settings/account'
    | '/settings/appearance'
    | '/projects/'
    | '/settings/'
    | '/projects/$projectSlug/settings'
    | '/projects/$projectSlug/'
    | '/projects/$projectSlug/boxes/$boxId'
    | '/projects/$projectSlug/boxes/create'
    | '/projects/$projectSlug/settings/github'
    | '/projects/$projectSlug/settings/llm-profiles'
    | '/projects/$projectSlug/settings/members'
    | '/projects/$projectSlug/settings/tavily'
    | '/projects/$projectSlug/settings/'
    | '/projects/$projectSlug/boxes/$boxId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  UsersRoute: typeof UsersRoute
  ProjectsProjectSlugRouteRoute: typeof ProjectsProjectSlugRouteRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/projects/$projectSlug': {
      id: '/projects/$projectSlug'
      path: '/projects/$projectSlug'
      fullPath: '/projects/$projectSlug'
      preLoaderRoute: typeof ProjectsProjectSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectSlug/': {
      id: '/projects/$projectSlug/'
      path: '/'
      fullPath: '/projects/$projectSlug/'
      preLoaderRoute: typeof ProjectsProjectSlugIndexRouteImport
      parentRoute: typeof ProjectsProjectSlugRouteRoute
    }
    '/projects/$projectSlug/settings': {
      id: '/projects/$projectSlug/settings'
      path: '/settings'
      fullPath: '/projects/$projectSlug/settings'
      preLoaderRoute: typeof ProjectsProjectSlugSettingsRouteRouteImport
      parentRoute: typeof ProjectsProjectSlugRouteRoute
    }
    '/projects/$projectSlug/settings/': {
      id: '/projects/$projectSlug/settings/'
      path: '/'
      fullPath: '/projects/$projectSlug/settings/'
      preLoaderRoute: typeof ProjectsProjectSlugSettingsIndexRouteImport
      parentRoute: typeof ProjectsProjectSlugSettingsRouteRoute
    }
    '/projects/$projectSlug/settings/tavily': {
      id: '/projects/$projectSlug/settings/tavily'
      path: '/tavily'
      fullPath: '/projects/$projectSlug/settings/tavily'
      preLoaderRoute: typeof ProjectsProjectSlugSettingsTavilyRouteImport
      parentRoute: typeof ProjectsProjectSlugSettingsRouteRoute
    }
    '/projects/$projectSlug/settings/members': {
      id: '/projects/$projectSlug/settings/members'
      path: '/members'
      fullPath: '/projects/$projectSlug/settings/members'
      preLoaderRoute: typeof ProjectsProjectSlugSettingsMembersRouteImport
      parentRoute: typeof ProjectsProjectSlugSettingsRouteRoute
    }
    '/projects/$projectSlug/settings/llm-profiles': {
      id: '/projects/$projectSlug/settings/llm-profiles'
      path: '/llm-profiles'
      fullPath: '/projects/$projectSlug/settings/llm-profiles'
      preLoaderRoute: typeof ProjectsProjectSlugSettingsLlmProfilesRouteImport
      parentRoute: typeof ProjectsProjectSlugSettingsRouteRoute
    }
    '/projects/$projectSlug/settings/github': {
      id: '/projects/$projectSlug/settings/github'
      path: '/github'
      fullPath: '/projects/$projectSlug/settings/github'
      preLoaderRoute: typeof ProjectsProjectSlugSettingsGithubRouteImport
      parentRoute: typeof ProjectsProjectSlugSettingsRouteRoute
    }
    '/projects/$projectSlug/boxes/create': {
      id: '/projects/$projectSlug/boxes/create'
      path: '/boxes/create'
      fullPath: '/projects/$projectSlug/boxes/create'
      preLoaderRoute: typeof ProjectsProjectSlugBoxesCreateRouteImport
      parentRoute: typeof ProjectsProjectSlugRouteRoute
    }
    '/projects/$projectSlug/boxes/$boxId': {
      id: '/projects/$projectSlug/boxes/$boxId'
      path: '/boxes/$boxId'
      fullPath: '/projects/$projectSlug/boxes/$boxId'
      preLoaderRoute: typeof ProjectsProjectSlugBoxesBoxIdRouteRouteImport
      parentRoute: typeof ProjectsProjectSlugRouteRoute
    }
    '/projects/$projectSlug/boxes/$boxId/': {
      id: '/projects/$projectSlug/boxes/$boxId/'
      path: '/'
      fullPath: '/projects/$projectSlug/boxes/$boxId/'
      preLoaderRoute: typeof ProjectsProjectSlugBoxesBoxIdIndexRouteImport
      parentRoute: typeof ProjectsProjectSlugBoxesBoxIdRouteRoute
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface ProjectsProjectSlugSettingsRouteRouteChildren {
  ProjectsProjectSlugSettingsGithubRoute: typeof ProjectsProjectSlugSettingsGithubRoute
  ProjectsProjectSlugSettingsLlmProfilesRoute: typeof ProjectsProjectSlugSettingsLlmProfilesRoute
  ProjectsProjectSlugSettingsMembersRoute: typeof ProjectsProjectSlugSettingsMembersRoute
  ProjectsProjectSlugSettingsTavilyRoute: typeof ProjectsProjectSlugSettingsTavilyRoute
  ProjectsProjectSlugSettingsIndexRoute: typeof ProjectsProjectSlugSettingsIndexRoute
}

const ProjectsProjectSlugSettingsRouteRouteChildren: ProjectsProjectSlugSettingsRouteRouteChildren =
  {
    ProjectsProjectSlugSettingsGithubRoute:
      ProjectsProjectSlugSettingsGithubRoute,
    ProjectsProjectSlugSettingsLlmProfilesRoute:
      ProjectsProjectSlugSettingsLlmProfilesRoute,
    ProjectsProjectSlugSettingsMembersRoute:
      ProjectsProjectSlugSettingsMembersRoute,
    ProjectsProjectSlugSettingsTavilyRoute:
      ProjectsProjectSlugSettingsTavilyRoute,
    ProjectsProjectSlugSettingsIndexRoute:
      ProjectsProjectSlugSettingsIndexRoute,
  }

const ProjectsProjectSlugSettingsRouteRouteWithChildren =
  ProjectsProjectSlugSettingsRouteRoute._addFileChildren(
    ProjectsProjectSlugSettingsRouteRouteChildren,
  )

interface ProjectsProjectSlugBoxesBoxIdRouteRouteChildren {
  ProjectsProjectSlugBoxesBoxIdIndexRoute: typeof ProjectsProjectSlugBoxesBoxIdIndexRoute
}

const ProjectsProjectSlugBoxesBoxIdRouteRouteChildren: ProjectsProjectSlugBoxesBoxIdRouteRouteChildren =
  {
    ProjectsProjectSlugBoxesBoxIdIndexRoute:
      ProjectsProjectSlugBoxesBoxIdIndexRoute,
  }

const ProjectsProjectSlugBoxesBoxIdRouteRouteWithChildren =
  ProjectsProjectSlugBoxesBoxIdRouteRoute._addFileChildren(
    ProjectsProjectSlugBoxesBoxIdRouteRouteChildren,
  )

interface ProjectsProjectSlugRouteRouteChildren {
  ProjectsProjectSlugSettingsRouteRoute: typeof ProjectsProjectSlugSettingsRouteRouteWithChildren
  ProjectsProjectSlugIndexRoute: typeof ProjectsProjectSlugIndexRoute
  ProjectsProjectSlugBoxesBoxIdRouteRoute: typeof ProjectsProjectSlugBoxesBoxIdRouteRouteWithChildren
  ProjectsProjectSlugBoxesCreateRoute: typeof ProjectsProjectSlugBoxesCreateRoute
}

const ProjectsProjectSlugRouteRouteChildren: ProjectsProjectSlugRouteRouteChildren =
  {
    ProjectsProjectSlugSettingsRouteRoute:
      ProjectsProjectSlugSettingsRouteRouteWithChildren,
    ProjectsProjectSlugIndexRoute: ProjectsProjectSlugIndexRoute,
    ProjectsProjectSlugBoxesBoxIdRouteRoute:
      ProjectsProjectSlugBoxesBoxIdRouteRouteWithChildren,
    ProjectsProjectSlugBoxesCreateRoute: ProjectsProjectSlugBoxesCreateRoute,
  }

const ProjectsProjectSlugRouteRouteWithChildren =
  ProjectsProjectSlugRouteRoute._addFileChildren(
    ProjectsProjectSlugRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  UsersRoute: UsersRoute,
  ProjectsProjectSlugRouteRoute: ProjectsProjectSlugRouteRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
