/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as BoxesCreateRouteImport } from './routes/boxes/create'
import { Route as BoxesBoxIdRouteImport } from './routes/boxes/$boxId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesCreateRoute = BoxesCreateRouteImport.update({
  id: '/boxes/create',
  path: '/boxes/create',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxesBoxIdRoute = BoxesBoxIdRouteImport.update({
  id: '/boxes/$boxId',
  path: '/boxes/$boxId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/users': typeof UsersRoute
  '/boxes/$boxId': typeof BoxesBoxIdRoute
  '/boxes/create': typeof BoxesCreateRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/users': typeof UsersRoute
  '/boxes/$boxId': typeof BoxesBoxIdRoute
  '/boxes/create': typeof BoxesCreateRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/users': typeof UsersRoute
  '/boxes/$boxId': typeof BoxesBoxIdRoute
  '/boxes/create': typeof BoxesCreateRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/users'
    | '/boxes/$boxId'
    | '/boxes/create'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/users'
    | '/boxes/$boxId'
    | '/boxes/create'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/users'
    | '/boxes/$boxId'
    | '/boxes/create'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  UsersRoute: typeof UsersRoute
  BoxesBoxIdRoute: typeof BoxesBoxIdRoute
  BoxesCreateRoute: typeof BoxesCreateRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes/create': {
      id: '/boxes/create'
      path: '/boxes/create'
      fullPath: '/boxes/create'
      preLoaderRoute: typeof BoxesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boxes/$boxId': {
      id: '/boxes/$boxId'
      path: '/boxes/$boxId'
      fullPath: '/boxes/$boxId'
      preLoaderRoute: typeof BoxesBoxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  UsersRoute: UsersRoute,
  BoxesBoxIdRoute: BoxesBoxIdRoute,
  BoxesCreateRoute: BoxesCreateRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
