"""Canonical container runtime port definition.

This is the authoritative Protocol for container runtimes.
box/ports/container_runtime.py re-exports this for convenience.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from codebox_orchestrator.compute.domain.entities import ContainerConfig, ContainerInfo


class ContainerRuntime(Protocol):
    def check_connection(self) -> str: ...
    def spawn(self, config: ContainerConfig) -> ContainerInfo: ...
    def stop(self, container_id_or_name: str) -> None: ...
    def start(self, container_id_or_name: str) -> None: ...
    def remove(self, container_id_or_name: str) -> None: ...
    def list_containers(self) -> list[dict]: ...
    def get_logs(self, container_id_or_name: str, tail: int = 200) -> str: ...
